to_do_list/list_app/do_list/urls.py
from django.urls import path
from . import views

app_name = 'app_list'

urlpatterns = [
    path('index',views.index.as_view(), name = "index"),
    path('login/',views.loginPage,name="login"),
    path('',views.signup,name="signup"),
    path('logout/',views.LogoutPage,name="logout"),
]

to_do_list/list_app/list_app/urls.py
from django.contrib import admin
from django.urls import path,include
from django.views.generic import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('do_list/',include('do_list.urls')),
    path('',RedirectView.as_view(url = 'do_list/')),
    
]

to_do_list/list_app/do_list/models.py
from django.db import models
from django.conf import settings
from django.contrib.auth.models import User

# Create your models here.

class name_list(models.Model):
    username = models.CharField(max_length = 50)     

    def __str__(self) -> str:
        return f"{self.username}"
    
class to_do_list(models.Model):
    
    user_list = models.CharField(max_length = 50)
    user_names_list = models.ForeignKey(User,on_delete=models.CASCADE,null=True)
    
    
    
    def __str__(self) -> str:
        return f"{self.user_list}"    

to_do_list/list_app/do_list/views.py
from django.shortcuts import render,redirect,HttpResponse
from django.urls import reverse
from . import models
from .models import to_do_list,name_list
from django.views.generic import ListView,View
from django.contrib.auth.models import User
from django.contrib.auth import authenticate,login,logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin

# If Login The Page Will Show
class index(LoginRequiredMixin,View):
    def get(self,request):
        all_info = to_do_list.objects.filter( user_names_list = request.user,)
        context = {'all_info': all_info,}
        return render(request,"list/index.html",context = context)
    
    def post(self,request):
        all_info = to_do_list.objects.filter( user_names_list = request.user,)
        context = {'all_info': all_info,}
        checked = request.POST.getlist('checked')
        add = request.POST.get('Add')
        delete = request.POST.get('delete')
        print("Successfully running")
        
        #This If block Execute Delete From DataBase
        if delete != None:
            if checked != []:
                    print('You Deselected',checked)
                    for i in checked:
                        for x in models.to_do_list.objects.all():
                            if i == str(x):
                                    x.delete()
                                    print("You successfully deleted")
                                    
            return render(request,"list/index.html",context = context)
        
        #This ElIf block Execute Add From DataBase
        elif add != None: 
                user_list_add = request.POST['add_list']
                names = models.to_do_list(user_list = user_list_add)
                user_id = User.objects.all()
                name_list_loop = models.name_list.objects.all()
                names.save()
                if user_list_add != '':
                    for i in name_list_loop:
                        for x in user_id:
                            if str(i.username == x.username):
                                print(user_list_add)
                                data = to_do_list(user_names_list = request.user,user_list = user_list_add)
                                data.save()
                                break
                        break
                    
                return redirect(reverse('app_list:index'))
            
#This is LoginPage CodeSector    
def loginPage(request):
    if request.POST:
        username = request.POST.get('username')
        password = request.POST.get('pass')
        user = authenticate(request,username=username,password=password)
        models.name_list.objects.create(username = username)
        if user is not None:
            login(request,user)
            
            return redirect('app_list:index')

        else:
            return HttpResponse("Your Password or username is incorrect!")
    return render(request,"list/login.html")


#This is Signup Page CodeSector 
def signup(request):
    if request.POST:
        username = request.POST.get('username')
        email = request.POST.get('email')
        password_1 = request.POST.get('pass1')
        password_2 = request.POST.get('pass2')
        if password_1 != password_2:
            return HttpResponse("Your Password and Confirm Password Not Same!")
        else:
            my_user = User.objects.create_user(username,email,password_1)
            my_user.save()
            return redirect(reverse('app_list:login'))
    return render(request,"list/signup.html")

#This is Logout Page CodeSector 
def LogoutPage(request):
    logout(request)
    models.name_list.objects.all().delete()
    return redirect('app_list:login')        


    

     
    
        
    






        

to_do_list/list_app/do_list/templates/list/index.html
{% extends 'base.html' %}

{%block content%}





    <a href = "{% url 'app_list:logout' %}"class = "move btn btn-success ">Logout</a>
    <h1 class = "heading1 flex justify-content-center d-flex flex-column bd-highlight mb-3  d-flex align-items-center">Hey! {{user.get_username}}</h1>
    <div class="wrapper">   
        <div class = " container p-3 d-flex justify-content-center d-flex flex-column bd-highlight mb-3  d-flex align-items-center box ">
            <h1 class = "heading">TO DO LIST</h1>
            <h1 class = "heading2"id="demo"></h1>
            
            <br>
        
            <form  onsubmit = "myfunction()" action = "" method = "POST">
                {% csrf_token %}
            
                    {% for info in all_info %}
                    
                        <li><input class = "form-check-input"  type="checkbox" name = "checked" value = "{{info.user_list}}">
                        <label for = "{{info.user_list}}">{{info.user_list}}</label></li>
                        <br>
                    
                    {% endfor %}
            
            
                <div class="users input-group">
                    <input class = "form-control" type = "text" id = "Title" for = {{user.get_username}} name = "add_list" placeholder="Add Your List 😊" autocomplete = "off" >
                    <button class = "btn btn-outline-success" name = "Add" value = "Add" type="submit">Add</button>
                    <button class = "btn btn-outline-danger" name = "delete"value = 'delete'type = "submit">Remove</button>
                </div>
                <br>
                
            </form>   
            </div>   
            
    </div>
    
        
            
      


    
    
    

{% endblock %}

to_do_list/list_app/templates/base.html
{% load static %}
<html lang="en">
<head>
   <meta charset="UTF-8">
   <meta name="viewport" content="width=device-width, initial-scale=1.0">
   <title>TO DO List</title>

   

   <!-- Bootstrap CSS -->
   <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

   <!--Custom Css-->
   <link rel="stylesheet" type = "text/css" href = "{% static '/css/style.css'%}">   
   
   
</head>
<body>

    

    {% block content %}
    {% endblock %}
    
   <!-- Option 1: Bootstrap Bundle with Popper -->
   <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

   <!--Custom JavaScript-->
   <script src="{% static '/java_script/index.js'%}"></script>

</body>
</html>